const Options_TinhTP = [
    { value: '0', label: 'Chọn Tỉnh/Thành phố...' },
    { value: '', label: 'Thành phố Cần Thơ' },
    { value: '', label: 'Thành phố Đà Nẵng' },
    { value: '', label: 'Thành phố Hà Nội' },
    { value: '', label: 'Thành phố Hải Phòng' },
    { value: '', label: 'Thành phố Hồ Chí Minh' },
    { value: '', label: 'Tỉnh An Giang' },
    { value: '', label: 'Tỉnh Bà Rịa - Vũng Tàu' },
    { value: '', label: 'Tỉnh Bạc Liêu' },
    { value: '', label: 'Tỉnh Bắc Giang' },
    { value: '', label: 'Tỉnh Bắc Kạn' },
    { value: '', label: 'Tỉnh Bắc Ninh' },
    { value: '', label: 'Tỉnh Bến Tre' },
    { value: '', label: 'Tỉnh Bình Dương' },
    { value: '', label: 'Tỉnh Bình Định' },
    { value: '', label: 'Tỉnh Bình Phước' },
    { value: '', label: 'Tỉnh Bình Thuận' },
    { value: '', label: 'Tỉnh Cà Mau' },
    { value: '', label: 'Tỉnh Cao Bằng' },
    { value: '', label: 'Tỉnh Đắk Lắk' },
    { value: '', label: 'Tỉnh Đắk Nông' },
    { value: '', label: 'Tỉnh Điện Biên' },
    { value: '', label: 'Tỉnh Đồng Nai' },
    { value: '', label: 'Tỉnh Đồng Tháp' },
    { value: '', label: 'Tỉnh Gia Lai' },
    { value: '', label: 'Tỉnh Hà Giang' },
    { value: '', label: 'Tỉnh Hà Nam' },
    { value: '', label: 'Tỉnh Hà Tĩnh' },
    { value: '', label: 'Tỉnh Hải Dương' },
    { value: '', label: 'Tỉnh Hậu Giang' },
    { value: '', label: 'Tỉnh Hoà Bình' },
    { value: '', label: 'Tỉnh Hưng Yên' },
    { value: '', label: 'Tỉnh Khánh Hòa' },
    { value: '', label: 'Tỉnh Kiên Giang' },
    { value: '', label: 'Tỉnh Kon Tum' },
    { value: '', label: 'Tỉnh Lai Châu' },
    { value: '', label: 'Tỉnh Lạng Sơn' },
    { value: '', label: 'Tỉnh Lào Cai' },
    { value: '', label: 'Tỉnh Lâm Đồng' },
    { value: '', label: 'Tỉnh Long An' },
    { value: '', label: 'Tỉnh Nam Định' },
    { value: '', label: 'Tỉnh Nghệ An' },
    { value: '', label: 'Tỉnh Ninh Bình' },
    { value: '', label: 'Tỉnh Ninh Thuận' },
    { value: '', label: 'Tỉnh Phú Thọ' },
    { value: '', label: 'Tỉnh Phú Yên' },
    { value: '', label: 'Tỉnh Quảng Bình' },
    { value: '', label: 'Tỉnh Quảng Nam' },
    { value: '', label: 'Tỉnh Quảng Ngãi' },
    { value: '', label: 'Tỉnh Quảng Ninh' },
    { value: '', label: 'Tỉnh Quảng Trị' },
    { value: '', label: 'Tỉnh Sóc Trăng' },
    { value: '', label: 'Tỉnh Sơn La' },
    { value: '', label: 'Tỉnh Tây Ninh' },
    { value: '', label: 'Tỉnh Thái Bình' },
    { value: '', label: 'Tỉnh Thái Nguyên' },
    { value: '', label: 'Tỉnh Thanh Hóa' },
    { value: '', label: 'Tỉnh Thừa Thiên Huế' },
    { value: '', label: 'Tỉnh Tiền Giang' },
    { value: '', label: 'Tỉnh Trà Vinh' },
    { value: '', label: 'Tỉnh Tuyên Quang' },
    { value: '', label: 'Tỉnh Vĩnh Long' },
    { value: '', label: 'Tỉnh Vĩnh Phúc' },
    { value: '', label: 'Tỉnh Yên Bái' },
]
export default Options_TinhTP;